/*
 Generated by typeshare 1.4.0
*/

export enum OAuthProvision {
	Auth = "auth",
	Location = "location",
	Calendar = "calendar",
}

export interface PublicConfig {
	redirect_to_first_oauth_provider: boolean;
	oauth_providers: Record<OAuthProvision, string[]>;
}

export enum LocationType {
	Address = "Address",
	Link = "Link",
	Other = "Other",
}

export interface CreateLocation {
	type_: LocationType;
	name: string;
	description?: string;
}

export enum PermissionLevel {
	Student = "Student",
	Teacher = "Teacher",
	Admin = "Admin",
}

export interface AdminUpdateUser {
	email_verified?: boolean;
	phone_number?: string | null;
	fname?: string;
	lname?: string;
	bio?: string | null;
	profile_image?: string;
	permission_level?: PermissionLevel;
}

export interface UpdateUser {
	phone_number?: string | null;
	fname?: string;
	lname?: string;
	bio?: string | null;
}

export interface Location {
	id: number;
	public: boolean;
	user_id: number;
	type_: LocationType;
	name: string;
	description?: string;
	created_on: string;
	updated_at: string;
}

export interface UpdateLocation {
	type_?: LocationType;
	name?: string;
	description?: string;
}

export interface Group {
	id: number;
	name: string;
	description?: string;
	public: boolean;
	created_on: string;
	updated_at: string;
}

export interface UpdateGroup {
	name?: string;
	description?: string;
	public?: boolean;
}

export interface CreateGroup {
	name: string;
	description?: string;
	public: boolean;
}

export interface UpdateIsMemberOf {
	assigned_teacher?: number;
}

export interface OAuthErrorMessage {
	error_msg: string;
}

export interface SignUpData {
	email: string;
	phone_number?: string;
	fname: string;
	lname: string;
	password: string;
}

export interface LoginData {
	email: string;
	password: string;
}

export interface LocalLoginData {
	updated_at: string;
}

export interface OAuthConnectionData {
	provider: string;
	created_on: string;
	updated_at: string;
}

export interface UserData {
	id: number;
	email: string;
	email_verified: boolean;
	phone_number?: string;
	fname: string;
	lname: string;
	bio?: string;
	profile_image?: string;
	permission_level: PermissionLevel;
	joined_on: string;
	updated_at: string;
	last_login?: string;
	local_login?: LocalLoginData;
	oauth_providers: Record<OAuthProvision, OAuthConnectionData[]>;
}

export interface PublicUserData {
	id: number;
	email: string;
	phone_number?: string;
	fname: string;
	lname: string;
	bio?: string;
	profile_image?: string;
	permission_level: PermissionLevel;
	joined_on: string;
}

export interface CreateLocalUser {
	email: string;
	phone_number?: string;
	fname: string;
	lname: string;
	permission_level?: PermissionLevel;
	password: string;
}

export interface MembershipData {
	group: Group;
	assigned_teacher?: PublicUserData;
}

