/*
 Generated by typeshare 1.4.0
*/

export interface UserData {
	username: string;
	email: string;
}

export interface CreateUser {
	username: string;
	email: string;
	password: string;
}

export interface LoginData {
	name_query: string;
	password: string;
}

